### ISSUE TITLE
[SWOC'24]Feature: Generate Random Inspirational Quotes Along with Author Name 

### ISSUE THREAD

**Issue by Anshul-Sharma01** [subh05sus/Python-Voice-Assistant#102]
**Feature Details**
I want to add a feature after which when the user asks for the quote ,the Jarvis can generate random inspirational quotes along with the author name

I am a SWOC 24 Contributor and want to work on this feature ,please assign this feature to me.

**Comment by DiyaChougule** [comment]
@subh05sus please assign me this isssue uder SWOC 24
