### ISSUE TITLE
[SWOC'24] PDF Reader using Jarvis

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [subh05sus/Python-Voice-Assistant#98]
**Is your feature request related to a problem? Please describe.**
- I would like to add the pdf reader functioning in Jarvis.

**Describe the solution you'd like**
- By using PDF reading libraries, etc.
- Add the code in 'else if' statement and implement the idea.

**Additional context**
- This will help user to read their pdf files, any kind of short notes, guidelines, books, etc.

**Comment by Avdhesh-Varshney** [comment]
@subh05sus please assign this project to me to contribute under SWOC'24

**Comment by subh05sus** [comment]
done
